#!/usr/bin/env bash
# Assemble a deterministic App Preview from the real Compose control-loop frames generated by
# marketing/site/generate-assets.sh. No Simulator window, coordinates, or user data are involved.
#
# Usage: assemble-compose.sh <en|zh> <frame_dir> <assets_dir> <final.mov>
set -euo pipefail

LANG_CODE="${1:-en}"
FRAMES="${2:?control-loop frame dir}"
ASSETS="${3:?overlay assets dir}"
FINAL="${4:?output mov}"
CW=("0.4,4.7" "4.9,9.6" "9.8,14.4" "14.6,19.8" "20.0,24.5" "25.0,29.2")

[ -f "$FRAMES/f00000.png" ] || { echo "missing Compose frames: $FRAMES" >&2; exit 1; }

# The 10.5-second product loop is slowed to 24.9 seconds so each real workflow state remains
# readable, then a five-second brand card closes the preview. App Store requires a stereo audio
# track even for a silent preview, so anullsrc supplies one.
ffmpeg -nostdin -y -loglevel error \
  -framerate 30 -i "$FRAMES/f%05d.png" \
  -loop 1 -t 5 -i "$ASSETS/logo.png" \
  -i "$ASSETS/cap1.png" -i "$ASSETS/cap2.png" -i "$ASSETS/cap3.png" \
  -i "$ASSETS/cap4.png" -i "$ASSETS/cap5.png" -i "$ASSETS/cap6.png" \
  -f lavfi -i anullsrc=channel_layout=stereo:sample_rate=48000 \
  -filter_complex "\
[0:v]scale=1320:2868:flags=lanczos,setpts=2.38*PTS,fps=30,trim=duration=24.9,setpts=PTS-STARTPTS[flow];\
[1:v]scale=1320:2868:flags=lanczos,fps=30,trim=duration=5,setpts=PTS-STARTPTS[end];\
[flow][end]concat=n=2:v=1[b];\
[b][2:v]overlay=0:0:enable='between(t,${CW[0]})'[v1];\
[v1][3:v]overlay=0:0:enable='between(t,${CW[1]})'[v2];\
[v2][4:v]overlay=0:0:enable='between(t,${CW[2]})'[v3];\
[v3][5:v]overlay=0:0:enable='between(t,${CW[3]})'[v4];\
[v4][6:v]overlay=0:0:enable='between(t,${CW[4]})'[v5];\
[v5][7:v]overlay=0:0:enable='between(t,${CW[5]})',scale=886:1920:flags=lanczos,setsar=1[v]" \
  -map "[v]" -map 8:a -t 29.9 -r 30 \
  -c:v libx264 -profile:v high -level 4.0 -pix_fmt yuv420p -b:v 11M -maxrate 12M -bufsize 24M \
  -c:a aac -b:a 256k -ar 48000 -ac 2 -movflags +faststart "$FINAL"

ffprobe -v error -select_streams v:0 \
  -show_entries stream=width,height,r_frame_rate -show_entries format=duration \
  -of default=noprint_wrappers=1 "$FINAL"
