package dev.ccpocket.daemon.disk

import dev.ccpocket.protocol.AgentKind
import dev.ccpocket.protocol.Decision
import dev.ccpocket.protocol.ExportFile
import dev.ccpocket.protocol.FileContent
import dev.ccpocket.protocol.Frame
import dev.ccpocket.protocol.PermissionAsk
import dev.ccpocket.protocol.PermissionMode
import dev.ccpocket.protocol.PermissionVerdict
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeout
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.nio.file.Files
import java.nio.file.Path
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/** The approval gate in front of ExportFile (issue #67 v2 / #79): changed-set fast path, owner
 *  approval for the widening, workdir binding, and the `..`/symlink containment red line. */
class FileExportServiceTest {

    @TempDir
    lateinit var tmp: Path

    private lateinit var workdir: Path

    private fun setUpProject(): Path {
        workdir = Files.createDirectories(tmp.resolve("proj"))
        Files.writeString(workdir.resolve("report.txt"), "generated by a script")
        return workdir
    }

    /** Frames the service emitted, in order; [next] waits for the following one. */
    private class Emitted {
        val frames = Channel<Frame>(Channel.UNLIMITED)
        val emit: suspend (Frame) -> Unit = { frames.send(it) }
        suspend fun next(): Frame = withTimeout(5_000) { frames.receive() }
    }

    private fun CoroutineScope.service(
        changed: Boolean = false,
        liveWorkdir: Path? = null,
        timeoutMs: Long = 30_000,
    ) = FileExportService(
        this,
        liveWorkdirOf = { liveWorkdir ?: workdir },
        isChanged = { _, _, _, _ -> changed },
        serveChanged = { _, wd, sid, p -> FileContent(wd, sid, p, text = "CHANGED-SET") },
        verdictTimeoutMs = timeoutMs,
    )

    private fun req(path: String) = ExportFile("c1", workdir.toString(), "s1", path, AgentKind.CLAUDE)

    // ── the four gate behaviors ─────────────────────────────────────────────

    @Test
    fun changed_set_path_serves_directly_without_an_ask() = runBlocking {
        setUpProject()
        val out = Emitted()
        service(changed = true).run(req("report.txt"), PermissionMode.DEFAULT, out.emit)
        val reply = out.next() as FileContent
        assertEquals("CHANGED-SET", reply.text) // the ReadFile-equivalent path, no widening
        assertTrue(out.frames.tryReceive().isFailure) // exactly one frame — never a PermissionAsk
    }

    @Test
    fun unchanged_path_raises_an_ask_and_serves_on_allow() = runBlocking {
        setUpProject()
        val out = Emitted()
        val svc = service()
        val job = launch { svc.run(req("report.txt"), PermissionMode.DEFAULT, out.emit) }
        val ask = out.next() as PermissionAsk
        assertEquals("ExportFile", ask.tool)
        assertEquals("c1", ask.convoId)
        assertEquals("report.txt", ask.inputPreview)
        assertTrue(svc.onVerdict(PermissionVerdict("c1", ask.askId, Decision.ALLOW)))
        job.join()
        val reply = out.next() as FileContent
        assertTrue(reply.ok)
        assertEquals("generated by a script", reply.text) // the REAL file, post-approval
    }

    @Test
    fun deny_verdict_refuses_with_a_readable_reason() = runBlocking {
        setUpProject()
        val out = Emitted()
        val svc = service()
        val job = launch { svc.run(req("report.txt"), PermissionMode.DEFAULT, out.emit) }
        val ask = out.next() as PermissionAsk
        assertTrue(svc.onVerdict(PermissionVerdict("c1", ask.askId, Decision.DENY)))
        job.join()
        val reply = out.next() as FileContent
        assertFalse(reply.ok)
        assertTrue("not approved" in reply.error!!, reply.error)
    }

    @Test
    fun dotdot_and_symlink_escapes_are_refused_without_ever_asking() = runBlocking {
        setUpProject()
        val secret = Files.writeString(tmp.resolve("secret.txt"), "outside the project")
        Files.createSymbolicLink(workdir.resolve("link.txt"), secret)

        for (path in listOf("../secret.txt", "link.txt")) {
            val out = Emitted()
            service().run(req(path), PermissionMode.DEFAULT, out.emit)
            val reply = out.next() as FileContent
            assertFalse(reply.ok, path)
            assertTrue("outside" in reply.error!!, "$path -> ${reply.error}")
            assertTrue(out.frames.tryReceive().isFailure, "an escape must never raise an ask: $path")
        }
    }

    // ── the surrounding contract ────────────────────────────────────────────

    @Test
    fun bypass_mode_serves_without_an_ask() = runBlocking {
        setUpProject()
        val out = Emitted()
        service().run(req("report.txt"), PermissionMode.BYPASS_PERMISSIONS, out.emit)
        val reply = out.next() as FileContent
        assertTrue(reply.ok)
        assertEquals("generated by a script", reply.text)
    }

    @Test
    fun always_allow_is_never_recorded_every_export_asks_again() = runBlocking {
        // approving ONE file must not silently open the whole tree (security review L1): the ask is
        // one-off (neverRemember), and even a client CLAIMING remember=true records nothing server-side
        setUpProject()
        val svc = service()
        val first = Emitted()
        val job = launch { svc.run(req("report.txt"), PermissionMode.DEFAULT, first.emit) }
        val ask = first.next() as PermissionAsk
        assertTrue(ask.neverRemember, "an export ask is a one-off decision — the UI must not offer Always allow")
        svc.onVerdict(PermissionVerdict("c1", ask.askId, Decision.ALLOW, remember = true))
        job.join()
        assertTrue((first.next() as FileContent).ok)

        // same convo, same path, straight after an allow+remember: the gate must prompt AGAIN
        val second = Emitted()
        val again = launch { svc.run(req("report.txt"), PermissionMode.DEFAULT, second.emit) }
        val askAgain = second.next()
        assertTrue(askAgain is PermissionAsk, "remember must never be recorded for exports")
        svc.onVerdict(PermissionVerdict("c1", (askAgain as PermissionAsk).askId, Decision.DENY))
        again.join()
    }

    @Test
    fun unanswered_ask_times_out_to_deny() = runBlocking {
        setUpProject()
        val out = Emitted()
        service(timeoutMs = 150).run(req("report.txt"), PermissionMode.DEFAULT, out.emit)
        assertTrue(out.next() is PermissionAsk)
        val reply = out.next() as FileContent
        assertFalse(reply.ok)
        assertTrue("not approved" in reply.error!!)
    }

    @Test
    fun export_is_bound_to_the_live_conversations_own_workdir() = runBlocking {
        setUpProject()
        val elsewhere = Files.createDirectories(tmp.resolve("other"))
        val out = Emitted()
        service(liveWorkdir = elsewhere).run(req("report.txt"), PermissionMode.DEFAULT, out.emit)
        val reply = out.next() as FileContent
        assertFalse(reply.ok)
        assertTrue("own project folder" in reply.error!!, reply.error)
        assertTrue(out.frames.tryReceive().isFailure) // refused before any ask
    }

    @Test
    fun closed_conversation_cannot_export_at_all() = runBlocking {
        setUpProject()
        val out = Emitted()
        FileExportService(
            this,
            liveWorkdirOf = { null }, // registry no longer knows this convo
            isChanged = { _, _, _, _ -> false },
        ).run(req("report.txt"), PermissionMode.DEFAULT, out.emit)
        val reply = out.next() as FileContent
        assertFalse(reply.ok)
        assertTrue("no longer open" in reply.error!!, reply.error)
    }

    @Test
    fun missing_file_refuses_with_a_readable_reason() = runBlocking {
        setUpProject()
        val out = Emitted()
        service().run(req("ghost.txt"), PermissionMode.DEFAULT, out.emit)
        val reply = out.next() as FileContent
        assertFalse(reply.ok)
        assertTrue("no longer exists" in reply.error!!, reply.error)
    }
}
