#!/usr/bin/env python3
"""Write site/assets/product/manifest.json — provenance for every generated marketing asset.

Called by generate-assets.sh; stdlib + ffprobe only, no build-time dependency for serving the site.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from pathlib import Path

GENERATOR = {
    "loop": "mobile/composeApp/src/desktopTest/kotlin/dev/ccpocket/app/showcase/ShowcaseRender.kt"
            "#renderSiteLoop",
    "desktop": "mobile/composeApp/src/desktopTest/kotlin/dev/ccpocket/app/desktop/"
               "DesktopScreenshotTest.kt#generate",
    "compose": "marketing/site/generate-assets.sh",
}

# (file, kind, language, generator key, human description)
ASSETS = [
    ("control-loop-en.mp4", "video", "en", "loop",
     "Watch, Approve, Continue and Inspect in one continuous session, recorded from the phone UI."),
    ("control-loop-zh.mp4", "video", "zh", "loop",
     "同一个会话里的查看、授权、继续、检查，取自手机端真实界面。"),
    ("control-loop-en-poster.jpg", "poster", "en", "loop",
     "Still of the approval decision — shown when motion is reduced or the video cannot load."),
    ("control-loop-zh-poster.jpg", "poster", "zh", "loop",
     "授权决策的静帧——减弱动效或视频加载失败时显示。"),
    ("desktop-console.png", "screenshot", "en", "desktop",
     "The desktop app's two-pane console: paired machines on the left, the live session on the right."),
    ("overview.png", "composite", "en", "compose",
     "README overview: the desktop console beside two stills from the same phone reel."),
]


def probe(path: Path) -> dict:
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-select_streams", "v:0",
         "-show_entries", "stream=width,height", "-show_entries", "format=duration",
         "-of", "json", str(path)],
        check=True, capture_output=True, text=True,
    ).stdout
    data = json.loads(out)
    stream = (data.get("streams") or [{}])[0]
    info: dict = {"width": stream.get("width"), "height": stream.get("height")}
    duration = (data.get("format") or {}).get("duration")
    if duration and path.suffix == ".mp4":
        info["durationSec"] = round(float(duration), 2)
    return info


def main() -> int:
    out_dir = Path(sys.argv[1]).resolve()
    fps = int(sys.argv[2]) if len(sys.argv) > 2 else 30

    assets = []
    for name, kind, lang, gen, description in ASSETS:
        path = out_dir / name
        if not path.exists() or path.stat().st_size == 0:
            print(f"missing or empty asset: {path}", file=sys.stderr)
            return 1
        entry = {
            "file": name,
            "kind": kind,
            "language": lang,
            "generator": GENERATOR[gen],
            "bytes": path.stat().st_size,
            "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
            "description": description,
            **probe(path),
        }
        if kind == "video":
            entry["fps"] = fps
            entry["audio"] = "none"
        assets.append(entry)

    manifest = {
        "$comment": "Generated by marketing/site/generate-assets.sh — do not hand-edit.",
        "provenance": {
            "source": "real product UI",
            "data": "scripted demo data",
            "statement": "Every asset here is the real Compose UI rendered offscreen from a scripted "
                         "demo script. It is mechanical product evidence, not customer validation: no "
                         "real user, repository, transcript, key or account is read or shown.",
            "statementZh": "这些素材都由真实 Compose 界面离屏渲染，数据是脚本化的演示数据。它是产品的机械"
                           "证据，不是客户背书：不读取、不展示任何真实用户、仓库、会话、密钥或账号。",
            "regenerate": "bash marketing/site/generate-assets.sh",
            "readme": "marketing/site/README.md",
        },
        "assets": assets,
    }
    (out_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(f"manifest: {len(assets)} assets → {out_dir / 'manifest.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
